server.port = 0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

brevo.api-key=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
brevo.from-email=challavenkatareddy2000@gmail.com
brevo.from-name=Chall Venkata Reddy