eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.routes[0].id=service-staff
spring.cloud.gateway.routes[0].uri=lb://SERVICE-STAFF
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/staff/**,/api/leave/**

spring.cloud.gateway.routes[1].id=service-patient
spring.cloud.gateway.routes[1].uri=lb://SERVICE-PATIENT
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/patient/**

spring.cloud.gateway.routes[2].id=service-appointment
spring.cloud.gateway.routes[2].uri=lb://SERVICE-APPOINTMENT
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/appointment/**

spring.cloud.gateway.routes[3].id=service-notification
spring.cloud.gateway.routes[3].uri=lb://SERVICE-NOTIFICATION
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/notification/email/**

spring.cloud.gateway.routes[4].id=service-staff-swagger
spring.cloud.gateway.routes[4].uri=lb://SERVICE-STAFF
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/staff-service/v3/api-docs/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/staff-service/v3/api-docs/(?<segment>.*), /v3/api-docs/${segment}

spring.cloud.gateway.routes[5].id=service-patient-swagger
spring.cloud.gateway.routes[5].uri=lb://SERVICE-PATIENT
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/patient-service/v3/api-docs
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/api/patient-service/v3/api-docs,/v3/api-docs

spring.cloud.gateway.routes[5].id=service-appointment-swagger
spring.cloud.gateway.routes[5].uri=lb://SERVICE-APPOINTMENT
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/appointment-service/v3/api-docs
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/api/appointment-service/v3/api-docs,/v3/api-docs

spring.cloud.gateway.routes[6].id=service-notification-swagger
spring.cloud.gateway.routes[6].uri=lb://SERVICE-NOTIFICATION
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/notification-service/email/v3/api-docs
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/api/notifications-service/email/v3/api-docs,/v3/api-docs

springdoc.swagger-ui.urls[0].name=SERVICE-STAFF
springdoc.swagger-ui.urls[0].url=/api/staff-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=SERVICE-PATIENT
springdoc.swagger-ui.urls[1].url=/api/patient-service/v3/api-docs

springdoc.swagger-ui.urls[2].name=SERVICE-APPOINTMENT
springdoc.swagger-ui.urls[2].url=/api/appointment-service/v3/api-docs

springdoc.swagger-ui.urls[3].name=SERVICE-NOTIFICATION
springdoc.swagger-ui.urls[3].url=/api/notification-service/email/v3/api-docs